name: Docker Build and Push

on:
  push:
    branches:
    - main

env:
  NODE_VERSION: 'v0.0.1'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: GitHub Action for DigitalOcean - doctl
      uses: digitalocean/action-doctl@v2.1.0
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
    - name: Build Docker Image]
      run: |
        doctl registry login --expiry-seconds 600
        docker build --tag registry.digitalocean.com/agilenav/ciconsoletest:${{ env.NODE_VERSION }} .
        docker push registry.digitalocean.com/agilenav/ciconsoletest:${{ env.NODE_VERSION }}
      
