name: Docker Build and Push

on:
  push:
    branches:
    - main

env:
  IMAGE_NAME: 'ciconsoletest'
  IMAGE_TAG: 'latest'
  DO_REGISTRY_URL: 'registry.digitalocean.com/agilenav'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: GitHub Action for DigitalOcean - doctl
      uses: digitalocean/action-doctl@v2.1.0
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
    - name: Build Docker Image]
      run: |
        doctl registry login --expiry-seconds 600
        docker build --tag ${{ env.DO_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        docker push ${{ env.DO_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      
